### ISSUE TITLE
Version v0.2.1 of plugin doen't work with ES 2.2.0

### ISSUE THREAD

**Issue by furio** [embulk/embulk-output-elasticsearch#23] opened 2016-02-18 16:36 UTC
I had transport exceptions.
By recompiling the gem using 2.2.0 of es jar it seems it is working (with es 2.2.0 and 2.1.x)

**Comment by sakama** [comment] 2016-02-19 01:43
Although tried both of ES 2.2.0 and 2.1.0, I couldn't reproduce.
Could you show us your config.yml and stacktrace?

**Comment by sakama** [comment] 2016-06-21 04:17
I closed this issue.
Please let us know when you find out procedure for reproducing.

Thanks.

**Closed as completed by sakama** 2016-06-21 04:17 UTC
